# Generated by Django 5.0.4 on 2024-05-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mwssage',
            new_name='message',
        ),
    ]
